### ISSUE TITLE
Feature request: support typing for query parameters

### ISSUE THREAD

**Issue by danvk** [danvk/crosswalk#5]
crosswalk currently types path parameters (`/path/to/:resource`) but leaves query parameters (`?key=value`) untyped. For endpoints that take query params, it would be great to have a way to type them. Ideally this would be checked on the request and make its way through to the swagger docs.

**Comment by mscottnelson** [comment]
Do you need any assistance getting this in? I’m currently evaluating crosswalk because I love the thought process and clean solution, and typed query params seems like a really useful inclusion.

**Comment by danvk** [comment]
Hi @mscottnelson, I'm aiming to get this change in this week. The main hangup in #9 and #13 is that the URL maker becomes somewhat ambiguous once you add query parameters. One way you could help is by telling us a little more about your use case. Would you be using this API to generate URLs (as opposed to making requests to them)? And do you use query parameters for anything but `GET` endpoints?

**Comment by danvk** [comment]
@CarterGrimmeisen @mscottnelson this is now part of `crosswalk@1.4.0`. Would love some feedback on how this is working once you pull it in!
